apiVersion: v1
kind: Service
metadata:
  name: ricettejdk-service
  namespace: jdk
spec:
  type: NodePort
  selector:
    app: backend
    service: ricette
  ports:
  - protocol: TCP
    nodePort: 31100
    port: 8080
    targetPort: 8080
 
